### ISSUE TITLE
brew formula installs linux binary

### ISSUE THREAD

**Issue by dafyk** [brandonskerritt/RustScan#16]
```
$ brew install rustscan
Updating Homebrew...
==> Installing rustscan from brandonskerritt/rustscan
==> Downloading https://github.com/brandonskerritt/RustScan/releases/download/1.0.1/rustscan.tar.gz
==> Downloading from https://github-production-release-asset-2e65be.s3.amazonaws.com/278933035/ee7d7e80-c9ca-11ea-8bc9-ff510bfbd428?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credent
######################################################################## 100.0%
🍺  /usr/local/Cellar/rustscan/1.0.1: 3 files, 3.6MB, built in 6 seconds

$ /usr/local/Cellar/rustscan/1.0.1/bin/rustscan
-bash: /usr/local/Cellar/rustscan/1.0.1/bin/rustscan: cannot execute binary file: Exec format error
$ file /usr/local/Cellar/rustscan/1.0.1/bin/rustscan
rustscan: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /home/linuxbrew/.linuxbrew/lib/ld.so, for GNU/Linux 3.2.0, with debug_info, not stripped
```
I also tried manualy downloading/running rustscan-1.0.1-x86_64.tar.gz but it is also Linux binary. Looks like you are missing macos build in releases section.

**Comment by brandonskerritt** [comment]
You are right! Give me an hour or so to update HomeBrew :)

**Comment by brandonskerritt** [comment]
Okay, theoretically speaking -- it works. I build the binary on the machine, so it should work. Although obviously as I only have a Mac, I cannot test. I will try testing it on Linux, but I have to reinstall Homebrew and my WiFi speed is very bad right now :)

**Comment by brandonskerritt** [comment]
I can confirm that this now works on Homebrew (via Linux).
Any Mac OS users, please test for me? :)

**Comment by dafyk** [comment]
Confirmed, it works. I see one minor problem, it still shows ```Try -B 2500.```. I am not going to open another issue as i saw earlier today PR to fix this.
