### ISSUE TITLE
Only open ports with no nmap scanning

### ISSUE THREAD

**Issue by 0xrishabh** [brandonskerritt/RustScan#24]
Is it possible to give a feature where you don't want to do nmap and just save open ports to a file.

**Comment by brandonskerritt** [comment]
That would be possible! Specifically, I want to add a grep mode. So you can do:
`rustscan 127.0.0.1 -G > file.txt` to output the ports to a file :)

**Comment by 0xrishabh** [comment]
Ya, that will be cool too.

**Comment by brandonskerritt** [comment]
This works in version 1.2, with `-q` for quiet mode.
It returns a string, so users will have to delete the quotes. But other than that, this will work (in the new version, not yet released)

```
> rustscan 127.0.0.1 -q > ports.txt
> cat ports.txt
"53,631,41710,46624"
```
