### ISSUE TITLE
SHA256 Hash mismatch on Brew Tap

### ISSUE THREAD

**Issue by cappellem** [brandonskerritt/RustScan#27]
Hi guys, receiving a SHA256 mismatch on the brew tap.
Error: SHA256 mismatch
Expected: **8eca05c7857beea8daee145342f3e28b0f03d87aa6d8c21265dab61e29c649d0**
     Actual: **25ad662ea0bd0095e658868ac46a9c5bad8a01b6389b0b2c520054b393cb647e**

Can i request the SHA256 Hash is updated please?

![image](https://user-images.githubusercontent.com/16210325/88280102-25aaa300-ccdd-11ea-9637-05272209204c.png)

**Comment by brandonskerritt** [comment]
Yup! I updated it as soon as I saw it. Super sorry, I'm checking to see if Homebrew works now :)
