### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by VoipSip** [brandonskerritt/RustScan#28]
how i can use already installation git clone https://github.com/brandonskerritt/RustScan.git

after done the installation i can't run on centos 7 

please give me all info about setup and the run commands on centos 

thank you

**Comment by brandonskerritt** [comment]
Howdy! Not sure about CentOS, but here's the steps:

1. Install Rust
`curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`
From their documentation: https://www.rust-lang.org/tools/install
2. Install RustScan
`cargo install rustscan`

This _should_ work :)

**Comment by brandonskerritt** [comment]
Howdy! Not sure about CentOS, but here's the general steps:

1. Git Clone
2. Install Rust
`curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`
From:
https://www.rust-lang.org/tools/install
3. Build
`cargo build --release`
4. The binary is located at `target/release/rustscan`
5. Place the binary wherever you want such as in /bin/, or symlink it, or something! :)

**Comment by VoipSip** [comment]
thank you for answer but see 
rustcan -b 500 -T 1500 192.168.0.1
-bash: rustcan: command not found
or 
target/release/rustscan
-bash: target/release/rustscan: No such file or directory

/root/RustScan < script is here after login by my server root and  cd RustScan

**Comment by brandonskerritt** [comment]
Hey!
The first issue is because rustscan is missing one letter 
> rustcan -b 500 -T 1500 192.168.0.1

The second issue might be because it is not actually executing? I have no idea how Cent OS works to be honest. But in regular bash, to execute it:
```
./target/release/rustscan
```

Do any of those work? :)

**Comment by VoipSip** [comment]
thank you already setup and working now but i got some error check plz 

target/release/rustscan -b 500 -T 1500 192.168.0.1

     _____           _    _____
    |  __ \         | |  / ____|
    | |__) |   _ ___| |_| (___   ___ __ _ _ __
    |  _  / | | / __| __|\___ \ / __/ _` | '_ \
    | | \ \ |_| \__ \ |_ ____) | (_| (_| | | | |
    |_|  \_\__,_|___/\__|_____/ \___\__,_|_| |_|
    Faster nmap scanning with rust.
 Automated Decryption Tool - https://github.com/ciphey/ciphey
 Creator https://github.com/brandonskerritt
Os { code: 113, kind: Other, message: "No route to host" }
thread 'main' panicked at 'Too many open files. Please reduce batch size. The default is 5000. Try -b 2500.',
 src/main.rs:178:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by bernardoamc** [comment]
The key message is: `Os { code: 113, kind: Other, message: "No route to host" }`, the important part being `"No route to host" `.

This means that this IP address is unreachable. 
Try it with a different IP besides this one, this might be the IP assigned to your router.

**Comment by VoipSip** [comment]
THANK YOU

**Comment by VoipSip** [comment]
TRY TO Support UDP

**Comment by bernardoamc** [comment]
Glad to help! 

> TRY TO Support UDP

For sure! 👍 

Do you mind if we close this issue @VoipSip ? <3

**Comment by VoipSip** [comment]
no thank you for your help
