### ISSUE TITLE
Nmap flag issue

### ISSUE THREAD

**Issue by 4rchiba** [brandonskerritt/RustScan#29]
Hello found your tool today and been trying to get my custom nmap flags to work. Reading the documentation it says passing flags after -- will provide them to nmap but im having no luck in doing so. 

https://i.imgur.com/1xfbuji.png

**Comment by brandonskerritt** [comment]
![image](https://user-images.githubusercontent.com/10378052/88282400-67d5e380-cce1-11ea-94f4-710167dde82e.png)

Weird! I can get it to work, and I can't seem to reproduce this bug :( How did you install RustScan?

**Comment by 4rchiba** [comment]
Hey thanks for the fast reply 
I installed on kali via https://github.com/brandonskerritt/RustScan/releases/tag/1.0.1 with dpkg -i on the file. It works just scanning an ip but wont allow me to modify nmap flags used.

**Comment by brandonskerritt** [comment]
Ah, I know why! Sooo... Version 1.1 is the one with custom nmap flags, and there isn't a .deb file for it. I am literally building the .deb for it right now, I'll let you know when it's done. I haven't automated this yet, my apologies! :)

**Comment by 4rchiba** [comment]
Ohh i see, your tool looks very interesting and have been looking for something like this for a while for pentesting where i can customize the nmap flags for my needs. Thank you for sharing it and your hard work, it has great potential. 

Looking forward to testing the nmap flag options.

**Comment by brandonskerritt** [comment]
@4rchiba Thanks so much!!! This is  still a very new project, so I'm hoping there's not _too_ many bugs. I hope pentesters find it useful, I sure do :D
Anyway, I released the .deb file.
https://github.com/brandonskerritt/RustScan/releases
Thanks again for being such a great supporter!
