### ISSUE TITLE
Crash on OSX 

### ISSUE THREAD

**Issue by benichmt1** [brandonskerritt/RustScan#36]
Installed with Homebrew, upon running I get the following error:

```Os { code: 24, kind: Other, message: "Too many open files" }
thread 'main' panicked at 'Too many open files. Please reduce batch size. The default is 5000. Try -B 2500.', src/main.rs:179:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace```

I'm on 10.15.5.

**Comment by Rackme** [comment]
Copy of #25

**Comment by brandonskerritt** [comment]
Yup! @Rackme is right. Reducing your batch count will help :)

**Comment by brandonskerritt** [comment]
Basically, your OS can only open so many connections before it crashes. I believe Mac OS is 254. You can see how to increase that using #25 and #21 for more info :)

**Comment by benichmt1** [comment]
I tried `rustcan -b 254` as suggested but still get the same error.

**Comment by brandonskerritt** [comment]
Hey! Run these 3 commands for me:

```
ulimit -a
ulimit -Hn
ulimit -Sn
```

And tell me what they output? They will show what the maximum number of open file descriptors is :)

**Comment by benichmt1** [comment]
>-n: file descriptors                256

**Comment by benichmt1** [comment]
Looks like 250 works, not 254.

**Comment by fuomag9** [comment]
Same issue on WSL2, see #39
