### ISSUE TITLE
Add a BIG disclaimer regarding the dangerousness of the tool

### ISSUE THREAD

**Issue by SakiiR** [brandonskerritt/RustScan#37]
It is cool to gain speed but careful ! 🚒 

When scanning a single IP, opening as much file descriptors (sockets) on the specified IP can be harmfull.

Example: "Do not use this tool against sensitive infrastructure blah blah blah"

**Comment by brandonskerritt** [comment]
Thank you! I will add this to the next release :)

**Comment by brandonskerritt** [comment]
@SakiiR Should I add this to #usage of the README and the help menu? And perhaps if file limit ls larger than X, it prints the warning too?

**Comment by brandonskerritt** [comment]
Adder disclaimer to README

**Comment by brandonskerritt** [comment]
This is now in the help menu, will show when I can get it to compile

**Comment by brandonskerritt** [comment]
Okay, it warns 4 times:

Once in help menu
Once on the README
When it suggests upping the ulimit, it warns (it does this twice in the code)
