### ISSUE TITLE
Show Nmap command to be run

### ISSUE THREAD

**Issue by Isona** [brandonskerritt/RustScan#51]
It would be helpful to print the Nmap command which will be run after the initial port scan is complete so that if Nmap crashes (or flags were forgotten) the command is easily recoverable.

**Comment by brandonskerritt** [comment]
This used to be default behavior, but I removed it a couple of days ago (when I was implementing custom nmap arguments). I'll add it back in :)

**Comment by brandonskerritt** [comment]
Done!
I will push to master branch now, and it should be out as 1.3 whenever I do that.
Here is what it's going to look like:

```rust
    if !quiet{
        println!("The Nmap command to be run is {}", string_format);
    }
```
