### ISSUE TITLE
Better Arch Linux PKGBUILd

### ISSUE THREAD

**Issue by brandonskerritt** [brandonskerritt/RustScan#55]
The current PKGBUILD file is:

```
# Maintainer: Bee <brandon@skerritt.blog>
pkgname=rustscan-bin
pkgver=1.2.0
pkgrel=1
pkgdesc="Faster Nmap Scanning with Rust"
url="https://github.com/brandonskerritt/rustscan"
license=("MIT")
arch=("x86_64")
provides=("rustscan")
depends=('rustup')

package() {
	rustup toolchain install stable && cargo install rustscan
}
```

This is not located in this repository. Instead, I cloned the AUR version to get the file.

I know very little about publishing to the AUR. 

This isn't a nice solution, at least I don't believe it to be, because it simply installs Rust and then uses Rust's Cargo to install RustScan.

With the Homebrew version, it downloads the tar file and builds the binary.
https://github.com/brandonskerritt/homebrew-rustscan/blob/master/Formula/rustscan.rb

Can someone with more Arch experience than I please make the PKGBUILD better, or help suggest how to make the install easier?

For reference, here is a list of related issues:
https://github.com/brandonskerritt/RustScan/issues/49
https://github.com/brandonskerritt/RustScan/issues/17

**Comment by brandonskerritt** [comment]
In particular, this is an issue with using the Cargo build:
```
be sure to add `/root/.cargo/bin` to your PATH to be able to run the installed binaries
```

By default, cargo is not in PATH. So the command `rustscan` will not work.

**Comment by brandonskerritt** [comment]
This crate may come in handy
https://crates.io/crates/cargo-aur

**Comment by imlonghao** [comment]
```
pkgname=rustscan
_pkgname=RustScan
pkgver=1.2.0
pkgrel=1
pkgdesc="Faster Nmap Scanning with Rust"
arch=("x86_64" "i686")
url="https://github.com/brandonskerritt/RustScan"
license=("GPL3")
provides=('rustscan')
conflicts=('rustscan')
depends=("glibc")
makedepends=("cargo")
source=("${pkgname}-${pkgver}.tar.gz::${url}/archive/${pkgver}.tar.gz")
sha256sums=('9f42e5f244aef46fca0b30076220a6a5cec8bfef1764ea9a3d76ffc458f6b292')

build() {
  cd ${_pkgname}-${pkgver}
  cargo build --release --locked --all-features --target-dir=target
}

package() {
  cd ${_pkgname}-${pkgver}
  install -Dm755 target/release/${pkgname} ${pkgdir}/usr/bin/${pkgname}
}

```

I write a PKGBUILD file following [Rust package guidelines](https://wiki.archlinux.org/index.php/Rust_package_guidelines), will upload it to AUR as package `rustscan` once #67 is fixed.
By the way, I'd like to file a delete or merge request to the current `rustscan-bin` AUR package since I think it is violating [AUR submission guidelines](https://wiki.archlinux.org/index.php/AUR_submission_guidelines), shouldn't name with `-bin`

**Comment by brandonskerritt** [comment]
Thanks so much!! I'll delete the rustscan-bin package now :)

**Comment by imlonghao** [comment]
I just test and upload to AUR and add you as co-maintainer.

https://aur.archlinux.org/packages/rustscan/

**Comment by brandonskerritt** [comment]
Thanks so much! I'll try to merge mine with yours. I've never done this before, but according to the wiki it's just an email / message :)

**Comment by imlonghao** [comment]
You don't need to do anything about the merge request.

**Comment by brandonskerritt** [comment]
@all-contributors please add @imlonghao for bugs, packaging & maintenance

**Comment by brandonskerritt** [comment]
Confirmed this is working, thank you so much! :)
