### ISSUE TITLE
Have you ever tried nmap --min-parallelism option?

### ISSUE THREAD

**Issue by nsforth** [brandonskerritt/RustScan#63]
RustScan Readme states that it's much more faster than nmap.
Nmap by default makes very polite scans to avoid detecting by firewall/IDS.
It makes sense. Slow undetected scan is more presice, because IDS may block attacking host and aggressive scan won't get useful information.
Ok, you want to be faster with nmap, let's try --min-parallelism:
```
$ nmap -Pn -PS -p1-65000 --min-parallelism=10000 8.8.8.8
Warning: Your --min-parallelism option is pretty high!  This can hurt reliability.
Starting Nmap 7.80 ( https://nmap.org ) at 2020-07-25 10:34 MSK
Nmap scan report for dns.google (8.8.8.8)
Host is up (0.067s latency).
Not shown: 64998 filtered ports
PORT    STATE SERVICE
53/tcp  open  domain
443/tcp open  https

Nmap done: 1 IP address (1 host up) scanned in 34.23 seconds
```
Pretty fast, isn't it?
There is a warning about scan reliability, of course.

P.S. It will be nice to update Readme page with fair comparison.

**Comment by brandonskerritt** [comment]
The gif on the README scans 8.8.8.8 in 8 seconds and gets all ports :p But I'll include this on the README 🤷‍♂️✨
