### ISSUE TITLE
The Cargo.lock file is out of date for version 1.2.0

### ISSUE THREAD

**Issue by imlonghao** [brandonskerritt/RustScan#67]
**Describe the bug**

Hello,

I am writing a PKGBUILD for arch user following the [Rust package guidelines](https://wiki.archlinux.org/index.php/Rust_package_guidelines)

But I am unable to build the package with the latest version 1.2.0. Cargo failed with the following error message.

```
==> Starting build()...
    Updating crates.io index
error: the lock file /build/rustscan/src/RustScan-1.2.0/Cargo.lock needs to be updated but --locked was passed to prevent this
If you want to try to generate the lock file without accessing the network, use the --offline flag.
```

**To Reproduce**

1. Download an untar https://github.com/brandonskerritt/RustScan/archive/1.2.0.tar.gz
2. Run `cargo build --release --locked --all-features --target-dir=target`

**Expected behavior**

I can build the binary

**Screenshots**

See the desc.

**Desktop (please complete the following information):**

 - OS: Archlinux
 - Version 1.2.0

**Smartphone (please complete the following information):**

N/A

**Additional context**

N/A

**Comment by brandonskerritt** [comment]
Hey! Thanks so much for submitting this issue, I appreciate it! 

This is fixed on master. The fix was:

```
cargo update
```

Annoying that is doesn't automatically update when I publish the package. My bad!

**Comment by imlonghao** [comment]
Thanks for your response.

Can you tag a new release with the correct Cargo.toml? Don't forget to update the file this time. :)

Thanks in advance~

**Comment by brandonskerritt** [comment]
Hey!

This should work now. The `cargo.lock` was in the `.gitignore`, which prevented me from uploading the file.
https://github.com/brandonskerritt/RustScan/releases/tag/1.2.2

Thanks so much!
